In [1]:
import pandas as pd

In [3]:
df = pd.read_parquet('../input/医疗器械分类目录_eb.parquet')

In [4]:
df.columns

Index(['一级序号/产品类别', '二级序号/产品类别', '三级序号/产品类别', '产品描述', '预期用途', '品名举例', '管理类别',
       '产品描述_eb', '预期用途_eb', '三级序号/产品类别_产品描述_预期用途_eb'],
      dtype='object')

In [5]:
df.head(5)

,一级序号/产品类别,二级序号/产品类别,三级序号/产品类别,产品描述,预期用途,品名举例,管理类别,产品描述_eb,预期用途_eb,三级序号/产品类别_产品描述_预期用途_eb
0,有源手术器械,超声手术设备及附件,超声手术设备,"通常由超声波发生器和带有外科尖端的手持部件组成,手持部件通常由一个换能器、一个连接构件和一个...",用于软组织的切割、止血、整形。,软组织超声手术仪、外科超声手术系统、超声手术系统、超声切割止血刀系统、软组织超声手术系统、超...,III,"[0.62452865, -0.08279847, 0.7706598, 0.2173354...","[-0.7767084, -0.44887084, 0.54603714, -0.47987...","[-0.06398521, -0.74084353, 1.0395542, -0.15914..."
1,有源手术器械,超声手术设备及附件,超声手术设备,"通常由主机、换能器和负压吸引装置组成,运用超声波能量使人体组织有选择性地被破碎,使其呈乳化态...",用于人体软组织的破碎、乳化。,超声脂肪乳化仪、超声外科吸引系统、软组织超声手术仪、软组织超声手术系统,III,"[0.7176996, 0.18667674, 1.3618044, -0.34847423...","[-0.0906311, -0.106743634, 1.0624038, -0.74863...","[0.3271185, -0.41710806, 1.7339445, -0.8219605..."
2,有源手术器械,超声手术设备及附件,超声手术设备,"通常由超声波发生器、手柄、刀头和冲洗部分组成,利用压电效应或者磁致伸缩效应将电能转化为超声能...",用于骨组织(包括牙齿)的切割和破碎。,超声骨科手术仪、超声骨组织手术系统,III,"[-0.10996862, -0.085446574, 1.5969005, -0.1290...","[-0.29867068, -0.43605462, 0.7567454, 0.061412...","[0.13799083, -0.7249332, 1.1923177, -0.0637142..."
3,有源手术器械,超声手术设备及附件,超声手术设备,"通常由主机、换能器、负压吸引和灌注装置组成,在内窥镜直视下将超声碎石头(变幅杆)接触结石,利...",用于泌尿系统结石的破碎。,超声碎石系统,III,"[1.099279, 0.384719, 1.4316646, -0.3465001, 0....","[0.35258812, 0.082277544, 0.86439824, -0.51611...","[0.4926535, -0.2330392, 1.5848159, -0.26080957..."
4,有源手术器械,超声手术设备及附件,高强度超声治疗设备,"通常由超声功率发生器、治疗头、控制装置等组成,一般采用聚焦或弱聚焦超声波。超声强度一般不超过...",用于手术及辅助治疗。,超声治疗仪、超声治疗系统、减脂聚焦超声治疗系统,III,"[0.41685078, 0.031113753, 1.0922213, -0.424051...","[-0.26038677, -0.8350986, 0.29387698, -0.47489...","[-0.15762489, -0.3907802, 1.3731759, -0.136146..."

In [6]:
df['完整结构'] = df['三级序号/产品类别'] + ':' + df['产品描述'] + ['预期用途']

In [7]:
df.head(5)

,一级序号/产品类别,二级序号/产品类别,三级序号/产品类别,产品描述,预期用途,品名举例,管理类别,产品描述_eb,预期用途_eb,三级序号/产品类别_产品描述_预期用途_eb,完整结构
0,有源手术器械,超声手术设备及附件,超声手术设备,"通常由超声波发生器和带有外科尖端的手持部件组成,手持部件通常由一个换能器、一个连接构件和一个...",用于软组织的切割、止血、整形。,软组织超声手术仪、外科超声手术系统、超声手术系统、超声切割止血刀系统、软组织超声手术系统、超...,III,"[0.62452865, -0.08279847, 0.7706598, 0.2173354...","[-0.7767084, -0.44887084, 0.54603714, -0.47987...","[-0.06398521, -0.74084353, 1.0395542, -0.15914...","超声手术设备:通常由超声波发生器和带有外科尖端的手持部件组成,手持部件通常由一个换能器、一个..."
1,有源手术器械,超声手术设备及附件,超声手术设备,"通常由主机、换能器和负压吸引装置组成,运用超声波能量使人体组织有选择性地被破碎,使其呈乳化态...",用于人体软组织的破碎、乳化。,超声脂肪乳化仪、超声外科吸引系统、软组织超声手术仪、软组织超声手术系统,III,"[0.7176996, 0.18667674, 1.3618044, -0.34847423...","[-0.0906311, -0.106743634, 1.0624038, -0.74863...","[0.3271185, -0.41710806, 1.7339445, -0.8219605...","超声手术设备:通常由主机、换能器和负压吸引装置组成,运用超声波能量使人体组织有选择性地被破碎..."
2,有源手术器械,超声手术设备及附件,超声手术设备,"通常由超声波发生器、手柄、刀头和冲洗部分组成,利用压电效应或者磁致伸缩效应将电能转化为超声能...",用于骨组织(包括牙齿)的切割和破碎。,超声骨科手术仪、超声骨组织手术系统,III,"[-0.10996862, -0.085446574, 1.5969005, -0.1290...","[-0.29867068, -0.43605462, 0.7567454, 0.061412...","[0.13799083, -0.7249332, 1.1923177, -0.0637142...","超声手术设备:通常由超声波发生器、手柄、刀头和冲洗部分组成,利用压电效应或者磁致伸缩效应将电..."
3,有源手术器械,超声手术设备及附件,超声手术设备,"通常由主机、换能器、负压吸引和灌注装置组成,在内窥镜直视下将超声碎石头(变幅杆)接触结石,利...",用于泌尿系统结石的破碎。,超声碎石系统,III,"[1.099279, 0.384719, 1.4316646, -0.3465001, 0....","[0.35258812, 0.082277544, 0.86439824, -0.51611...","[0.4926535, -0.2330392, 1.5848159, -0.26080957...","超声手术设备:通常由主机、换能器、负压吸引和灌注装置组成,在内窥镜直视下将超声碎石头(变幅杆..."
4,有源手术器械,超声手术设备及附件,高强度超声治疗设备,"通常由超声功率发生器、治疗头、控制装置等组成,一般采用聚焦或弱聚焦超声波。超声强度一般不超过...",用于手术及辅助治疗。,超声治疗仪、超声治疗系统、减脂聚焦超声治疗系统,III,"[0.41685078, 0.031113753, 1.0922213, -0.424051...","[-0.26038677, -0.8350986, 0.29387698, -0.47489...","[-0.15762489, -0.3907802, 1.3731759, -0.136146...","高强度超声治疗设备:通常由超声功率发生器、治疗头、控制装置等组成,一般采用聚焦或弱聚焦超声波..."

In [8]:
df.to_parquet('../output/医疗器械分类目录_eb_with_full_structure.parquet')